### ISSUE TITLE
update bottom plate file

### ISSUE THREAD

**Issue by basfora** [cornellmotionstudio/DIYDrone#1]
Find and update .STL file for the bottom plate of the frame (with the holes for attaching the gimbal)

**Comment by basfora** [comment]
> Find and update .STL file for the bottom plate of the frame (with the holes for attaching the gimbal)

New [CAD file added](https://github.com/cornellmotionstudio/DIYDrone/blob/master/frame/stls/bottom-plate-new.SLDPRT), please
1. verify it's the correct one
2. Create sliced and ready to print files
3. Update repo

**Comment by lerrylei** [comment]
Updated bottom plate files in the repo
